# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ukv-f4F7TyG-tZf4gN0wrfkhqulveFxc
"""

import numpy as np
import matplotlib.pyplot as plt

# import dataset as numpy array

x=np.array([1,2,3,4,5])
y=np.array([1,3,2,3,5])
# reshape the array
x=x.reshape(-1,1)
# print the x,y valuse
print("display the x array:",x)
print("display the y array:",y)

# plotting the scatter plot
plt.scatter(x,y, label="Data printed")

# import linear recogression module
from sklearn.linear_model import LinearRegression
# create a linear recogression module
model=LinearRegression();

# fit the module

model.fit(x, y)

# Get the value of Intercept and coefficient

intercept=model.intercept_
coefficient=model.coef_

# print the values
print(f'Intercept:{intercept}')
print(f'Coefficient:{coefficient}')

# pridection form the value
y_pred=model.predict(x)

# plotting the recogression
plt.plot(x,y_pred,color='blue',label="LinearRecogression")

# plotting setting
plt.xlabel('X-values')
plt.ylabel('Y-values')
plt.title('simple linear recogression')
plt.legend()

# display the graph
plt.show()

# predict the next element
x_new=np.array([[6]])
y_prid=model.predict(x_new);
print(f"Predicted value for X_new: {y_pred[0]}")