# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OrjkscL7ZMegZZFFNMN7FieuQfyx43Zi
"""

import numpy as np
import matplotlib.pyplot as plt

# Example data
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 3.5, 3.9, 5.1, 5.8])

# Reshape x to be a column vector if needed
x = x.reshape(-1, 1)

# Plotting the scatter plot
plt.scatter(x, y, label='Data points')

# Linear regression
from sklearn.linear_model import LinearRegression

# Create a linear regression model
model = LinearRegression()

# Fit the model
model.fit(x, y)

# Get the intercept and coefficient
intercept = model.intercept_
coefficients = model.coef_

print(f'Intercept: {intercept}')
print(f'Coefficient(s): {coefficients}')

# Predictions from the model
y_pred = model.predict(x)

# Plotting the regression line
plt.plot(x, y_pred, color='red', label='Linear regression')

# Plotting settings
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Scatter Plot with Linear Regression')
plt.legend()

# Display plot
plt.show()